name: CtrlpanelCore
options:
  bundleIdPrefix: com.ctrlaltdeseat
  deploymentTarget:
    macOS: '10.13'
    iOS: '11.0'
targets:
  CtrlpanelCore:
    type: framework
    platform: [iOS, macOS]
    sources: Sources
    scheme: {}
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    dependencies:
      - carthage: JSBridge
      - carthage: PromiseKit
